### ISSUE TITLE
Print profile points missing

### ISSUE THREAD

**Issue by TheSpirit** [huddleboards/maker-world-extension#1]
HI.
Great chrome extension, but you are missing the print profile points.

**Comment by huddleboards** [comment]
Thanks! One of the next tasks for this extension is to add the reward points to the print profile page in a similar look and feel to the uploads page below. Perhaps it makes sense to show the download and the print profile points on the same page, but I'll have to think about if it makes sense to show how many points each print profile has or just a total. 

  
![image](https://github.com/huddleboards/maker-world-extension/assets/77246919/47b68441-ed58-4e3e-a90f-419cd891fc01)

**Comment by TheSpirit** [comment]
i would like to see under the images all points. so download points, print profile points and then the total points of both.

**Comment by huddleboards** [comment]
Absolutely, that's the direction that I'll be heading with it after reviewing the options.
